//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minestrone
{
    
    
    /// <summary>
    /// The MinestroneSection Configuration Section.
    /// </summary>
    public partial class MinestroneSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the MinestroneSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string MinestroneSectionSectionName = "minestroneSection";
        
        /// <summary>
        /// Gets the MinestroneSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public static global::Minestrone.MinestroneSection Instance
        {
            get
            {
                return ((global::Minestrone.MinestroneSection)(global::System.Configuration.ConfigurationManager.GetSection(global::Minestrone.MinestroneSection.MinestroneSectionSectionName)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Minestrone.MinestroneSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::Minestrone.MinestroneSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Mappings Property
        /// <summary>
        /// The XML name of the <see cref="Mappings"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string MappingsPropertyName = "mappings";
        
        /// <summary>
        /// Gets or sets maps old IDs to new IDs yearly
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("Maps old IDs to new IDs yearly")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Minestrone.MinestroneSection.MappingsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Minestrone.Mappings Mappings
        {
            get
            {
                return ((global::Minestrone.Mappings)(base[global::Minestrone.MinestroneSection.MappingsPropertyName]));
            }
            set
            {
                base[global::Minestrone.MinestroneSection.MappingsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Minestrone
{
    
    
    /// <summary>
    /// The Mapping Configuration Element.
    /// </summary>
    public partial class Mapping : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region SourceId Property
        /// <summary>
        /// The XML name of the <see cref="SourceId"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string SourceIdPropertyName = "sourceId";
        
        /// <summary>
        /// Gets or sets the SourceId.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The SourceId.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Minestrone.Mapping.SourceIdPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual int SourceId
        {
            get
            {
                return ((int)(base[global::Minestrone.Mapping.SourceIdPropertyName]));
            }
            set
            {
                base[global::Minestrone.Mapping.SourceIdPropertyName] = value;
            }
        }
        #endregion
        
        #region TargetId Property
        /// <summary>
        /// The XML name of the <see cref="TargetId"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string TargetIdPropertyName = "targetId";
        
        /// <summary>
        /// Gets or sets the TargetId.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The TargetId.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Minestrone.Mapping.TargetIdPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual int TargetId
        {
            get
            {
                return ((int)(base[global::Minestrone.Mapping.TargetIdPropertyName]));
            }
            set
            {
                base[global::Minestrone.Mapping.TargetIdPropertyName] = value;
            }
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string NamePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Minestrone.Mapping.NamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::Minestrone.Mapping.NamePropertyName]));
            }
            set
            {
                base[global::Minestrone.Mapping.NamePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Minestrone
{
    
    
    /// <summary>
    /// A collection of Mapping instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::Minestrone.Mapping), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::Minestrone.Mappings.MappingPropertyName)]
    public partial class Mappings : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::Minestrone.Mapping"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string MappingPropertyName = "mapping";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override string ElementName
        {
            get
            {
                return global::Minestrone.Mappings.MappingPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::Minestrone.Mappings.MappingPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::Minestrone.Mapping)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::Minestrone.Mapping"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::Minestrone.Mapping"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::Minestrone.Mapping();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::Minestrone.Mapping"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Minestrone.Mapping"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Minestrone.Mapping this[int index]
        {
            get
            {
                return ((global::Minestrone.Mapping)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::Minestrone.Mapping"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::Minestrone.Mapping"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Minestrone.Mapping this[object name]
        {
            get
            {
                return ((global::Minestrone.Mapping)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::Minestrone.Mapping"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="mapping">The <see cref="global::Minestrone.Mapping"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Add(global::Minestrone.Mapping mapping)
        {
            base.BaseAdd(mapping);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::Minestrone.Mapping"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="mapping">The <see cref="global::Minestrone.Mapping"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Remove(global::Minestrone.Mapping mapping)
        {
            base.BaseRemove(this.GetElementKey(mapping));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::Minestrone.Mapping"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Minestrone.Mapping"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Minestrone.Mapping GetItemAt(int index)
        {
            return ((global::Minestrone.Mapping)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::Minestrone.Mapping"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::Minestrone.Mapping"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Minestrone.Mapping GetItemByKey(string name)
        {
            return ((global::Minestrone.Mapping)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
